version: "3.9"
services: 
  api:
    build: ./api
    ports: ["5000:80"]
  api_database:
    image: postgis/postgis
    env_file: [".env"]
  etl_database:
    image: postgis/postgis
    env_file: ['./arp_pipeline/db.env']
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
  arp_pipeline:
    build: ./arp_pipeline
    volumes:
      - ./erap-data/:/output
      - ./data:/data
    links:
      - "etl_database:db"
  scheduler:
    build: ./arp_pipeline
    command: poetry run luigid --address 0.0.0.0 --port 8082 --pidfile /luigid/luigid.pid --state-path /luigid/state.dat
    volumes:
      - ./luigid:/luigid
    ports:
      - "8082:8082"
  jupyter:
    build: ./notebooks
    links:
      - "etl_database:db"
